INSERT INTO body (name) VALUES ('седан');
INSERT INTO body (name) VALUES ('хэтчбек');
INSERT INTO body (name) VALUES ('хэтчбек 3 дв.');
INSERT INTO body (name) VALUES ('хэтчбек 5 дв.');
INSERT INTO body (name) VALUES ('лифтбек');
INSERT INTO body (name) VALUES ('внедорожники');
INSERT INTO body (name) VALUES ('внедорожник 3 дв.');
INSERT INTO body (name) VALUES ('внедорожник 5 дв.');
INSERT INTO body (name) VALUES ('универсал');
INSERT INTO body (name) VALUES ('купе');
INSERT INTO body (name) VALUES ('минивэн');
INSERT INTO body (name) VALUES ('пикап');
INSERT INTO body (name) VALUES ('лимузин');
INSERT INTO body (name) VALUES ('фургон');
INSERT INTO body (name) VALUES ('кабриолет');
